---
name: Publish package to GitHub Packages
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com
          # Defaults to the user or organization that owns the workflow file
          scope: "@octocat"

      - id: pnpm-cache-config
        shell: bash
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Cache NPM dependencies
        id: deps-cache
        with:
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: |
            ${{ steps.pnpm-cache-config.outputs.pnpm_cache_dir }}
            **/node_modules
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install deps (with cache)
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
