---
name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@octocat"

      - id: pnpm-cache-config
        shell: bash
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Cache NPM dependencies
        id: deps-cache
        with:
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: |
            ${{ steps.pnpm-cache-config.outputs.pnpm_cache_dir }}
            **/node_modules
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install deps (with cache)
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          preset: conventionalchangelog
          github-token: ${{ secrets.github_token }}
          git-user-name: "GitHub Actions [bot]"
          git-user-email: "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
