---
name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}
      change_log: ${{ steps.changelog.outputs.clean_changelog }}
      version: ${{ steps.changelog.outputs.version }}
      tag: ${{ steps.changelog.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@octocat"

      - id: pnpm-cache-config
        shell: bash
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Cache NPM dependencies
        id: deps-cache
        with:
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: |
            ${{ steps.pnpm-cache-config.outputs.pnpm_cache_dir }}
            **/node_modules
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install deps (with cache)
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          preset: conventionalcommits
          skip-on-empty: false
          github-token: ${{ secrets.github_token }}
          git-user-name: "GitHub Actions [bot]"
          git-user-email: "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Release
        id: create-release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: actions/github-script@v6
        env:
          RELEASE_TAG: ${{ steps.changelog.outputs.tag }}
          RELEASE_LOG: ${{ steps.changelog.outputs.clean_changelog }}
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `${process.env.RELEASE_TAG}`,
              name: `${process.env.RELEASE_TAG}`,
              body: `${process.env.RELEASE_LOG}`,
              draft: false,
              prerelease: false,
              make_latest: 'legacy'
            });
            return data.id
